### ISSUE TITLE
Load error in Insomina 2020.4.2

### ISSUE THREAD

**Issue by eramos** [devhammed/insomnia-plugin-documenter#1]
Error: Cannot find module 'mkdirp'

![imagen](https://user-images.githubusercontent.com/427821/100855356-5ddfa080-348a-11eb-891e-886414fbe197.png)

**Comment by devhammed** [comment]
How do you install it (it seems you just downloaded the repo archive from GitHub)?

**Comment by eramos** [comment]
Yes! That's it. Am I missing something?

**Comment by devhammed** [comment]
> Yes! That's it. Am I missing something?

Yes, you have to install it from Insomnia interface to automate install dependencies or just go to the Insomnia plugin hub link (https://insomnia.rest/plugins/insomnia-plugin-documenter) and click 'Install in Core', it should open Insomnia and prompt to install.

**Comment by eramos** [comment]
Great! It works , thanks

**Comment by devhammed** [comment]
> Great! It works , thanks

You're welcome 😁
