### ISSUE TITLE
Move All Resources Locally

### ISSUE THREAD

**Issue by RobertKlohr** [devhammed/insomnia-plugin-documenter#10]
### CSS and Web Fonts
Currently the index.html written by the documenter has an external reference for some of the CSS and web fonts used in the page. The prevents the page from rendering correctly on system with no internet access.

```html
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
    integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
```

I have been able to hack together a workaround doing the following:

1. I downloaded the 6.0 version of Font Awesome Free removed all the files except all.css and fa-solid-900.woff2 using the folder structure: 
```
/fontawesome
  /css
    all.css
  /webfonts
    fa-solid-900.woff2
```
2. I then copied the index.html file and original external link above with the one below.
```html
<link href="/fontawesome/css/all.css" rel="stylesheet" />
```
3. After exporting my collection from Insomnia I copy the folder structure from step 1 above into the export directory and they overwrite the index.html file with the one I edited.

Ideally you could make include the web font file and the css file in the plugin along with making edits to the index.html file so that all the needed resources were local.

There is one area for improvement that I, not being a web developer, was not able to figure out. The all.css file in the Font Awesome download is 121KB while there is another file called v4-font-face.css in that download that is only 2KB. The v4-font-face.css works for all but the Example Toggle Icon in the upper right of the page. If you can determine the css code to add then the overall plugin size will only increase by about 126 KB, being the small css plus the 124KB for the web font.

### Run In Insomnia Button
The run.svg image and the URI used in the button are external.

My request is to move the run.svg file to be local to the plugin and update the bundle.js file to that the URI in the button points to;
```
insomnia://app/import?uri=<protocol><host>/insomnia.json
```

**Comment by devhammed** [comment]
@RobertKlohr This issue should be created in the insodoc plugin repo.
