### ISSUE TITLE
Where is the option 'Export HTML Documentation' in insomnia?

### ISSUE THREAD

**Issue by riibeirogabriel** [devhammed/insomnia-plugin-documenter#2]
I have been installed the plugin in insomnia designer, but i didn't find this option to generate the docs

**Comment by devhammed** [comment]
> I have been installed the plugin in insomnia designer, but i didn't find this option to generate the docs

Click on the workspace name at the top left corner in Insomnia app, you should see it in the plugins menu group.

**Comment by riibeirogabriel** [comment]
This option doesn't exists in isnomnia designer, i think that this plugin was designed to default insomnia app, but i can install this plugin in plugins section of insomnia desginer.

**Comment by devhammed** [comment]
> This option doesn't exists in isnomnia designer, i think that this plugin was designed to default insomnia app, but i can install this plugin in plugins section of insomnia desginer.

Oh, yes it will only work in Insomnia Core, I honestly skipped the "designer" word in your comment.
