### ISSUE TITLE
Failed to install - Yarn error

### ISSUE THREAD

**Issue by pilotkid** [devhammed/insomnia-plugin-documenter#7]
Hello, I am currently facing an issue. I am trying to install insomnia-plugin-documenter. However, I keep getting a yarn error when installing via the UI. 

![image](https://user-images.githubusercontent.com/6385285/114258223-52ddd500-9982-11eb-840b-37bbfd00b396.png)

>Error: Yarn error warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
    at file:///C:/Users/Marcello/AppData/Local/insomnia/app-2020.5.2/resources/app.asar/bundle.js:103518:16
    at ChildProcess.exithandler (child_process.js:295:7)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:223:5)
    at Pipe.<anonymous> (net.js:664:12)
![image](https://user-images.githubusercontent.com/6385285/114258251-920c2600-9982-11eb-9512-a208e24370de.png)

**Comment by devhammed** [comment]
The project is created with npm so kindly install it globally before trying to install the plugin so Insomnia can use it to install dependencies.

**Comment by pilotkid** [comment]
Hello it is installed globally with npm, however, the error still persists.

**Comment by devhammed** [comment]
I think you got it wrong, I didn't say you should install the plugin itself globally, I meant you need to have npm so Insomnia can use it instead of yarn.

If it is still not working, you need to open an issue on the repo instead, this doesn't have anything to do with the plugin but Insomnia installation system instead.
